# Generated by Django 6.0.5 on 2026-05-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='long_url',
            new_name='original_url',
        ),
    ]
